# 04_smr_coloc_and_regional_plots.R
#
# Supports:
# - Table 1 colocalization columns
# - Supplementary Table 5
# - Supplementary Table 6
# - Supplementary Table 7
# - Figure 4
# - Supplementary Figures 2-4

source("scripts/00_helpers.R")
paths <- read_paths()
out_dir <- make_outdir(file.path(paths[["out_dir"]], "04_smr_coloc"))

process_smr_tables <- function(smr_twas, smr_mwas, smr_cpg_to_gene, out_prefix) {
  twas <- read_table_auto(smr_twas)
  mwas <- read_table_auto(smr_mwas)
  cpg_gene <- read_table_auto(smr_cpg_to_gene)

  write_tsv(twas, paste0(out_prefix, "_Supplementary_Table_5_SMR_TWAS_genes.tsv"))
  write_tsv(mwas, paste0(out_prefix, "_Supplementary_Table_6_SMR_MWAS_CpGs.tsv"))
  write_tsv(cpg_gene, paste0(out_prefix, "_Supplementary_Table_7_SMR_CpG_to_gene.tsv"))
  invisible(list(twas = twas, mwas = mwas, cpg_gene = cpg_gene))
}

process_coloc_tables <- function(eqtl_gwas, mqtl_gwas, out_prefix) {
  eqtl <- read_table_auto(eqtl_gwas)
  mqtl <- read_table_auto(mqtl_gwas)

  eqtl <- arrange(eqtl, desc(PP.H4.abf))
  mqtl <- arrange(mqtl, desc(PP.H4.abf))

  write_tsv(eqtl, paste0(out_prefix, "_coloc_eQTL_GWAS.tsv"))
  write_tsv(mqtl, paste0(out_prefix, "_coloc_mQTL_GWAS.tsv"))
  invisible(list(eqtl = eqtl, mqtl = mqtl))
}

plot_locus <- function(df, p_col, title, region_start, region_end,
                       ld_col = NULL, highlight = NULL) {
  df <- df %>% mutate(logp = -log10(pmax(as.numeric(.data[[p_col]]), .Machine$double.xmin)))
  aes_color <- if (!is.null(ld_col) && ld_col %in% names(df)) aes(color = .data[[ld_col]]) else NULL
  p <- ggplot(df, aes(x = BP, y = logp)) +
    geom_point(aes_color, alpha = 0.85, size = 1.4) +
    coord_cartesian(xlim = c(region_start, region_end)) +
    labs(title = title, x = NULL, y = expression(-log[10](P))) +
    theme_pg()

  if (!is.null(highlight) && nrow(highlight) > 0) {
    p <- p +
      geom_point(data = highlight, aes(x = BP, y = -log10(.data[[p_col]])),
                 inherit.aes = FALSE, shape = 23, fill = "white",
                 color = "black", size = 3) +
      geom_text(data = highlight, aes(x = BP, y = -log10(.data[[p_col]]), label = label),
                inherit.aes = FALSE, vjust = -1, size = 3)
  }
  p
}

plot_gene_track <- function(gene_anno, chr, region_start, region_end, target_gene = NULL) {
  genes <- read_table_auto(gene_anno) %>%
    filter(chr == paste0("chr", chr), start <= region_end, end >= region_start) %>%
    distinct(gene_name, start, end, .keep_all = TRUE) %>%
    arrange(start) %>%
    mutate(y = row_number(), is_target = gene_name == target_gene)

  ggplot(genes) +
    geom_segment(aes(x = pmax(start, region_start), xend = pmin(end, region_end),
                     y = y, yend = y, color = is_target), linewidth = 1) +
    geom_text(aes(x = (pmax(start, region_start) + pmin(end, region_end)) / 2,
                  y = y + 0.2, label = gene_name, color = is_target), size = 3) +
    scale_color_manual(values = c("TRUE" = "#c5372f", "FALSE" = "#333333"), guide = "none") +
    coord_cartesian(xlim = c(region_start, region_end)) +
    labs(x = "Position (bp)", y = NULL, title = "Genes") +
    theme_pg() +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
}

make_regional_plot <- function(gwas_region, qtl_region, gene_anno, chr,
                               region_start, region_end, target_gene, out_file) {
  gwas <- read_table_auto(gwas_region)
  qtl <- read_table_auto(qtl_region)
  h1 <- gwas %>% arrange(P_GWAS) %>% slice(1) %>% mutate(label = SNP)
  h2 <- qtl %>% arrange(P_QTL) %>% slice(1) %>% mutate(label = SNP)

  p1 <- plot_locus(gwas, "P_GWAS", paste0("GWAS: ", target_gene),
                   region_start, region_end, highlight = h1)
  p2 <- plot_locus(qtl, "P_QTL", paste0("QTL: ", target_gene),
                   region_start, region_end, highlight = h2)
  p3 <- plot_gene_track(gene_anno, chr, region_start, region_end, target_gene)

  if (requireNamespace("cowplot", quietly = TRUE)) {
    final <- cowplot::plot_grid(p1, p2, p3, ncol = 1, align = "v", rel_heights = c(1, 1, 0.8))
  } else {
    final <- p1
  }
  make_outdir(dirname(out_file))
  ggsave(out_file, final, width = 8, height = 6)
  invisible(final)
}

out_prefix <- file.path(out_dir, "smr_coloc")
process_smr_tables(paths[["smr_twas"]], paths[["smr_mwas"]], paths[["smr_cpg_to_gene"]], out_prefix)
process_coloc_tables(paths[["coloc_eqtl_gwas"]], paths[["coloc_mqtl_gwas"]], out_prefix)

# Regional plots are generated by calling make_regional_plot() with the per-locus
# GWAS/QTL files deposited in paths[["regional_plot_inputs"]].
